main:
  - identifier: about
    name: About
    url: /about
    weight: 1
  # - identifier: events
  #   name: Events
  #   url: /event/
  #   weight: 60
  - identifier: videos
    name: Videos
    url: /video/
    weight: 60
  - identifier: meetup
    name: Meetup
    url: https://www.meetup.com/JAMstack-nyc/
    weight: 90    
  # - identifier: speakers
  #   name: Speakers
  #   url: /speakers/
  #   weight: 60
  # - identifier: sponsors
  #   name: Sponsors
  #   url: /sponsors/
  #   weight: 60  